name:                simple-server
version:             0.1.0.0
github:              "marcteves/simple-server"
license:             BSD3
author:              "Marc Teves"
maintainer:          "gmarc.teves@gmail.com"
copyright:           "2019 Marc Teves"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple-server#readme>

dependencies:
- base >= 4.7 && < 5
- http-types
- warp
- wai
- bytestring
- aeson
- containers
- text
- simple-server-internal

library:
  source-dirs: src

executables:
  simple-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-server

tests:
  simple-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-server
